# Loop while we can find a prime factor
# each iteration of the loop calculate the prime factor of the 
# new number generated by the division of the previous number by the previous prime number

max_prime_factor<-function(number){
  prime<-2
  while(prime<round(number)){
    if(number%%prime==0)
      number<-number/prime
    prime<-prime+1    
  }
  return(prime)
}

system.time(
  print(max_prime_factor(600851475143))
)

# result : 6857
